### ISSUE TITLE
Something happened and our Oompa Loompas are working on it

### ISSUE THREAD

**Issue by hitokiri** [docker-taiga/taiga#18] opened 2019-04-22 19:49 UTC
hello y run the docker-compos but not found
![umpalumpas](https://user-images.githubusercontent.com/247528/56523837-64afde80-6505-11e9-8261-3d67d62ebc2a.png)

**Comment by w1ck3dg0ph3r** [comment] 2019-04-24 05:47
Hi! I'm afraid we need more to help you with this)
Post your env file, browser console logs, and logs from front and back containers, please.

**Comment by hitokiri** [comment] 2019-04-24 13:18
the webconsole print this

app.js:3244 WebSocket connection to 'ws://taiga.lan/events/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

**Comment by hitokiri** [comment] 2019-04-24 13:34
angular.js:11756 OPTIONS http://taiga.lan/api/v1/stats/discover net::ERR_NAME_NOT_RESOLVED
(anonymous) @ angular.js:11756
g @ angular.js:11517
c @ angular.js:11227
a @ angular.js:15961
(anonymous) @ angular.js:15977
$eval @ angular.js:17229
$digest @ angular.js:17045
$apply @ angular.js:17337
(anonymous) @ angular.js:17633
o @ angular.js:5869
(anonymous) @ angular.js:6145
setTimeout (async)
c.defer @ angular.js:6143
k @ angular.js:17632
$applyAsync @ angular.js:17366
u @ angular.js:11569
_ @ angular.js:11778
k.onload @ angular.js:11711
load (async)
(anonymous) @ angular.js:11694
g @ angular.js:11517
c @ angular.js:11227
a @ angular.js:15961
(anonymous) @ angular.js:15977
$eval @ angular.js:17229
$digest @ angular.js:17045
$apply @ angular.js:17337
(anonymous) @ angular.js:1749
a @ angular.js:4665
a @ angular.js:1747
ot @ angular.js:1767
(anonymous) @ app-loader.js:1
(anonymous) @ jquery.js:3366
l @ jquery.js:3187
add @ jquery.js:3246
(anonymous) @ jquery.js:3365
each @ jquery.js:365
(anonymous) @ jquery.js:3361
Deferred @ jquery.js:3427
then @ jquery.js:3360
(anonymous) @ app-loader.js:1
load @ l.js:120
(anonymous) @ l.js:123
(anonymous) @ l.js:98
n @ l.js:99
load (async)
p @ l.js:56
loadjs @ l.js:100
m @ l.js:80
load @ l.js:123
(anonymous) @ app-loader.js:1
l @ jquery.js:3187
fireWith @ jquery.js:3317
r @ jquery.js:8757
(anonymous) @ jquery.js:9123
load (async)
send @ jquery.js:9142
ajax @ jquery.js:8656
ot.(anonymous function) @ jquery.js:8807
getJSON @ jquery.js:8788
(anonymous) @ app-loader.js:1
(anonymous) @ app-loader.js:1
angular.js:11756 OPTIONS http://taiga.lan/api/v1/projects?discover_mode=true&order_by=-total_fans_last_week net::ERR_NAME_NOT_RESOLVED
(anonymous) @ angular.js:11756
g @ angular.js:11517
c @ angular.js:11227
a @ angular.js:15961
(anonymous) @ angular.js:15977
$eval @ angular.js:17229
$digest @ angular.js:17045
$apply @ angular.js:17337
(anonymous) @ angular.js:17633
o @ angular.js:5869
(anonymous) @ angular.js:6145
setTimeout (async)
c.defer @ angular.js:6143
k @ angular.js:17632
$applyAsync @ angular.js:17366
u @ angular.js:11569
_ @ angular.js:11778
k.onload @ angular.js:11711
load (async)
(anonymous) @ angular.js:11694
g @ angular.js:11517
c @ angular.js:11227
a @ angular.js:15961
(anonymous) @ angular.js:15977
$eval @ angular.js:17229
$digest @ angular.js:17045
$apply @ angular.js:17337
(anonymous) @ angular.js:1749
a @ angular.js:4665
a @ angular.js:1747
ot @ angular.js:1767
(anonymous) @ app-loader.js:1
(anonymous) @ jquery.js:3366
l @ jquery.js:3187
add @ jquery.js:3246
(anonymous) @ jquery.js:3365
each @ jquery.js:365
(anonymous) @ jquery.js:3361
Deferred @ jquery.js:3427
then @ jquery.js:3360
(anonymous) @ app-loader.js:1
load @ l.js:120
(anonymous) @ l.js:123
(anonymous) @ l.js:98
n @ l.js:99
load (async)
p @ l.js:56
loadjs @ l.js:100
m @ l.js:80
load @ l.js:123
(anonymous) @ app-loader.js:1
l @ jquery.js:3187
fireWith @ jquery.js:3317
r @ jquery.js:8757
(anonymous) @ jquery.js:9123
load (async)
send @ jquery.js:9142
ajax @ jquery.js:8656
ot.(anonymous function) @ jquery.js:8807
getJSON @ jquery.js:8788
(anonymous) @ app-loader.js:1
(anonymous) @ app-loader.js:1
angular.js:11756 OPTIONS http://taiga.lan/api/v1/projects?discover_mode=true&order_by=-total_activity_last_week net::ERR_NAME_NOT_RESOLVED
(anonymous) @ angular.js:11756
g @ angular.js:11517
c @ angular.js:11227
a @ angular.js:15961
(anonymous) @ angular.js:15977
$eval @ angular.js:17229
$digest @ angular.js:17045
$apply @ angular.js:17337
(anonymous) @ angular.js:17633
o @ angular.js:5869
(anonymous) @ angular.js:6145
setTimeout (async)
c.defer @ angular.js:6143
k @ angular.js:17632
$applyAsync @ angular.js:17366
u @ angular.js:11569
_ @ angular.js:11778
k.onload @ angular.js:11711
load (async)
(anonymous) @ angular.js:11694
g @ angular.js:11517
c @ angular.js:11227
a @ angular.js:15961
(anonymous) @ angular.js:15977
$eval @ angular.js:17229
$digest @ angular.js:17045
$apply @ angular.js:17337
(anonymous) @ angular.js:1749
a @ angular.js:4665
a @ angular.js:1747
ot @ angular.js:1767
(anonymous) @ app-loader.js:1
(anonymous) @ jquery.js:3366
l @ jquery.js:3187
add @ jquery.js:3246
(anonymous) @ jquery.js:3365
each @ jquery.js:365
(anonymous) @ jquery.js:3361
Deferred @ jquery.js:3427
then @ jquery.js:3360
(anonymous) @ app-loader.js:1
load @ l.js:120
(anonymous) @ l.js:123
(anonymous) @ l.js:98
n @ l.js:99
load (async)
p @ l.js:56
loadjs @ l.js:100
m @ l.js:80
load @ l.js:123
(anonymous) @ app-loader.js:1
l @ jquery.js:3187
fireWith @ jquery.js:3317
r @ jquery.js:8757
(anonymous) @ jquery.js:9123
load (async)
send @ jquery.js:9142
ajax @ jquery.js:8656
ot.(anonymous function) @ jquery.js:8807
getJSON @ jquery.js:8788
(anonymous) @ app-loader.js:1
(anonymous) @ app-loader.js:1
angular.js:11756 OPTIONS http://taiga.lan/api/v1/projects?discover_mode=true&is_featured=true net::ERR_NAME_NOT_RESOLVED
(anonymous) @ angular.js:11756
g @ angular.js:11517
c @ angular.js:11227
a @ angular.js:15961
(anonymous) @ angular.js:15977
$eval @ angular.js:17229
$digest @ angular.js:17045
$apply @ angular.js:17337
(anonymous) @ angular.js:17633
o @ angular.js:5869
(anonymous) @ angular.js:6145
setTimeout (async)
c.defer @ angular.js:6143
k @ angular.js:17632
$applyAsync @ angular.js:17366
u @ angular.js:11569
_ @ angular.js:11778
k.onload @ angular.js:11711
load (async)
(anonymous) @ angular.js:11694
g @ angular.js:11517
c @ angular.js:11227
a @ angular.js:15961
(anonymous) @ angular.js:15977
$eval @ angular.js:17229
$digest @ angular.js:17045
$apply @ angular.js:17337
(anonymous) @ angular.js:1749
a @ angular.js:4665
a @ angular.js:1747
ot @ angular.js:1767
(anonymous) @ app-loader.js:1
(anonymous) @ jquery.js:3366
l @ jquery.js:3187
add @ jquery.js:3246
(anonymous) @ jquery.js:3365
each @ jquery.js:365
(anonymous) @ jquery.js:3361
Deferred @ jquery.js:3427
then @ jquery.js:3360
(anonymous) @ app-loader.js:1
load @ l.js:120
(anonymous) @ l.js:123
(anonymous) @ l.js:98
n @ l.js:99
load (async)
p @ l.js:56
loadjs @ l.js:100
m @ l.js:80
load @ l.js:123
(anonymous) @ app-loader.js:1
l @ jquery.js:3187
fireWith @ jquery.js:3317
r @ jquery.js:8757
(anonymous) @ jquery.js:9123
load (async)
send @ jquery.js:9142
ajax @ jquery.js:8656
ot.(anonymous function) @ jquery.js:8807
getJSON @ jquery.js:8788
(anonymous) @ app-loader.js:1
(anonymous) @ app-loader.js:1
app.js:3244 WebSocket connection to 'ws://taiga.lan/events/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
t.setupConnection @ app.js:3244
r @ lodash.js:4935
r @ app.js:647
a @ angular.js:4665
(anonymous) @ angular.js:4473
r @ angular.js:322
ne @ angular.js:4473
a @ angular.js:1746
ot @ angular.js:1767
(anonymous) @ app-loader.js:1
(anonymous) @ jquery.js:3366
l @ jquery.js:3187
add @ jquery.js:3246
(anonymous) @ jquery.js:3365
each @ jquery.js:365
(anonymous) @ jquery.js:3361
Deferred @ jquery.js:3427
then @ jquery.js:3360
(anonymous) @ app-loader.js:1
load @ l.js:120
(anonymous) @ l.js:123
(anonymous) @ l.js:98
n @ l.js:99
angular.js:13550 WebSocket error: [object Event]
(anonymous) @ angular.js:13550
t.onError @ app.js:3487
r @ lodash.js:4935
error (async)
t.setupConnection @ app.js:3247
r @ lodash.js:4935
r @ app.js:647
a @ angular.js:4665
(anonymous) @ angular.js:4473
r @ angular.js:322
ne @ angular.js:4473
a @ angular.js:1746
ot @ angular.js:1767
(anonymous) @ app-loader.js:1
(anonymous) @ jquery.js:3366
l @ jquery.js:3187
add @ jquery.js:3246
(anonymous) @ jquery.js:3365
each @ jquery.js:365
(anonymous) @ jquery.js:3361
Deferred @ jquery.js:3427
then @ jquery.js:3360
(anonymous) @ app-loader.js:1
load @ l.js:120
(anonymous) @ l.js:123
(anonymous) @ l.js:98
n @ l.js:99
load (async)
p @ l.js:56
loadjs @ l.js:100
m @ l.js:80
load @ l.js:123
(anonymous) @ app-loader.js:1
l @ jquery.js:3187
fireWith @ jquery.js:3317
r @ jquery.js:8757
(anonymous) @ jquery.js:9123
load (async)
send @ jquery.js:9142
ajax @ jquery.js:8656
ot.(anonymous function) @ jquery.js:8807
getJSON @ jquery.js:8788
(anonymous) @ app-loader.js:1
(anonymous) @ app-loader.js:1
14WebSocket connection to 'ws://taiga.lan/events/' failed: WebSocket is closed before the connection is established.
app.js:3244 WebSocket connection to 'ws://taiga.lan/events/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
t.setupConnection @ app.js:3244
r @ lodash.js:4935
angular.js:13550 WebSocket error: [object Event]
(anonymous) @ angular.js:13550
t.onError @ app.js:3487
r @ lodash.js:4935
error (async)
t.setupConnection @ app.js:3247
r @ lodash.js:4935
setTimeout (async)
t.onClose @ app.js:3496
r @ lodash.js:4935
app.js:3244 WebSocket connection to 'ws://taiga.lan/events/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
t.setupConnection @ app.js:3244
r @ lodash.js:4935
angular.js:13550 WebSocket error: [object Event]
(anonymous) @ angular.js:13550
t.onError @ app.js:3487
r @ lodash.js:4935
error (async)
t.setupConnection @ app.js:3247
r @ lodash.js:4935
setTimeout (async)
t.onClose @ app.js:3496
r @ lodash.js:4935
app.js:3244 WebSocket connection to 'ws://taiga.lan/events/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
t.setupConnection @ app.js:3244
r @ lodash.js:4935
angular.js:13550 WebSocket error: [object Event]
(anonymous) @ angular.js:13550
t.onError @ app.js:3487
r @ lodash.js:4935
error (async)
t.setupConnection @ app.js:3247
r @ lodash.js:4935
setTimeout (async)
t.onClose @ app.js:3496
r @ lodash.js:4935
app.js:3244 WebSocket connection to 'ws://taiga.lan/events/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
t.setupConnection @ app.js:3244
r @ lodash.js:4935
angular.js:13550 WebSocket error: [object Event]
(anonymous) @ angular.js:13550
t.onError @ app.js:3487
r @ lodash.js:4935
error (async)
t.setupConnection @ app.js:3247
r @ lodash.js:4935
setTimeout (async)
t.onClose @ app.js:3496
r @ lodash.js:4935
app.js:3244 WebSocket connection to 'ws://taiga.lan/events/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
t.setupConnection @ app.js:3244
r @ lodash.js:4935
angular.js:13550 WebSocket error: [object Event]
(anonymous) @ angular.js:13550
t.onError @ app.js:3487
r @ lodash.js:4935
error (async)
t.setupConnection @ app.js:3247
r @ lodash.js:4935
setTimeout (async)
t.onClose @ app.js:3496
r @ lodash.js:4935
app.js:3244 WebSocket connection to 'ws://taiga.lan/events/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
t.setupConnection @ app.js:3244
r @ lodash.js:4935
angular.js:13550 WebSocket error: [object Event]
(anonymous) @ angular.js:13550
t.onError @ app.js:3487
r @ lodash.js:4935
error (async)
t.setupConnection @ app.js:3247
r @ lodash.js:4935
setTimeout (async)
t.onClose @ app.js:3496
r @ lodash.js:4935
app.js:3244 WebSocket connection to 'ws://taiga.lan/events/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
t.setupConnection @ app.js:3244
r @ lodash.js:4935
angular.js:13550 WebSocket error: [object Event]
(anonymous) @ angular.js:13550
t.onError @ app.js:3487
r @ lodash.js:4935
error (async)
t.setupConnection @ app.js:3247
r @ lodash.js:4935
setTimeout (async)
t.onClose @ app.js:3496
r @ lodash.js:4935
app.js:3244 WebSocket connection to 'ws://taiga.lan/events/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
t.setupConnection @ app.js:3244
r @ lodash.js:4935
angular.js:13550 WebSocket error: [object Event]
(anonymous) @ angular.js:13550
t.onError @ app.js:3487
r @ lodash.js:4935
error (async)
t.setupConnection @ app.js:3247
r @ lodash.js:4935
setTimeout (async)
t.onClose @ app.js:3496
r @ lodash.js:4935
app.js:3244 WebSocket connection to 'ws://taiga.lan/events/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
t.setupConnection @ app.js:3244
r @ lodash.js:4935
angular.js:13550 WebSocket error: [object Event]
(anonymous) @ angular.js:13550
t.onError @ app.js:3487
r @ lodash.js:4935
error (async)
t.setupConnection @ app.js:3247
r @ lodash.js:4935
setTimeout (async)
t.onClose @ app.js:3496
r @ lodash.js:4935
app.js:3244 WebSocket connection to 'ws://taiga.lan/events/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
t.setupConnection @ app.js:3244
r @ lodash.js:4935
angular.js:13550 WebSocket error: [object Event]
(anonymous) @ angular.js:13550
t.onError @ app.js:3487
r @ lodash.js:4935
error (async)
t.setupConnection @ app.js:3247
r @ lodash.js:4935
setTimeout (async)
t.onClose @ app.js:3496
r @ lodash.js:4935
app.js:3244 WebSocket connection to 'ws://taiga.lan/events/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
t.setupConnection @ app.js:3244
r @ lodash.js:4935
angular.js:13550 WebSocket error: [object Event]

**Comment by hitokiri** [comment] 2019-04-24 17:11
Hello, I was able to solve the problem thanks

**Comment by JosephCastro** [comment] 2019-05-10 19:08
Hi
What was the solution?

**Comment by chartchai** [comment] 2019-05-11 01:06
I found the same problem,
The taiga-back container show that "Trying iport local.py settings...." and then stop response. When I browse to the url, I found the image as hitokiri found"

**Comment by w1ck3dg0ph3r** [comment] 2019-05-17 08:05
Hi, it seems like TAIGA_HOST was not set up, leaving it at default `taiga.lan`, which was not resolvable.

**Comment by pierrejean** [comment] 2019-05-22 10:42
Sorry, same problem but time to time. First fresh start is ok but second one fail. 

It's look like an error on taiga-back : http://taiga.lan/api/v1/auth 
The answer is : nginx 502 Bad Gateway

The log of nginx into taiga-back
*1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.2, server: , request: "POST /api/v1/auth HTTP/1.0", upstream: "http://127.0.0.1:8000/api/v1/auth", host: "taiga.lan"

**Comment by michaelr-iq** [comment] 2019-05-29 19:27
I was having a similar issue that was showing the same error.
In my server, I had an Apache reverse proxy that was forwarding traffic to the nginx container.
To get it to work properly, I had to make the following changes:

Enable mod_proxy_http in apache httpd (reverse-proxy) in the httpd.conf, like so:

LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

Use X-Forwarded-For to log the IP in nginx (upstream) as mentioned here http://nginx.org/en/docs/http/ngx_http_realip_module.html.

Credit to user wurtel from serverfault.com.

Another change that I had to do is updating the TAIGA host to be as my external host.

For example, the server's entry point was `taiga.myDomain.com`
so I updated the TAIGA_HOST to be `taiga.myDomain.com`

Hopefully it helps some one else that might stumble upon the same issue.

**Comment by w1ck3dg0ph3r** [comment] 2019-09-27 08:32
@pierrejean Sorry, I cant reproduce this on default containers (i.e., not using another reverse proxy on top of taiga-proxy or integrating taiga-proxy config into said reverse proxy).
Also, as @michaelr-iq pointed out, TAIGA_HOST should be set up to an external hostname.

**Comment by w1ck3dg0ph3r** [comment] 2019-09-27 08:33
Closing this for now, as original issue was resolved.
@pierrejean If the problem persists, please open another one with exact environment and steps to reproduce the issue.

**Closed as completed by w1ck3dg0ph3r** 2019-09-27 08:33 UTC
