### ISSUE TITLE
Something happened and the Taiga has captured the error to be able to work on it.

### ISSUE THREAD

**Issue by Yersi88** [docker-taiga/taiga#48] opened 2021-01-17 13:14 UTC
After installation, when I visit the website I get above error.

**Comment by ivanflorentin** [comment] 2021-01-20 17:45
+1

**Comment by coindroid42** [comment] 2021-01-26 05:08
I changed host, and all work!!!

**Comment by rogerioadris** [comment] 2021-02-01 17:35
+1

**Comment by w1ck3dg0ph3r** [comment] 2021-02-04 05:21
Can't reproduce this. Could you provide any more relevant info?

**Comment by marshalleq** [comment] 2021-02-13 21:41
> I changed host, and all work!!!

What do you mean you changed host?

**Comment by Zakkaruu** [comment] 2021-02-18 18:27
I tried this in Ubuntu 20.04 and ProtonOS 4.0RC both as VMs in VMware Workstation. The error message was displayed at http://localhost:9000 in both environments when used with the default docker-compose.yml file. After editing the docker-compose.yml file and modifying these lines
` TAIGA_SITES_DOMAIN: "localhost:9000"` && `TAIGA_URL: "http://localhost:9000"` to include the specific IP ` TAIGA_SITES_DOMAIN: "10.241.13.163:9000"` && `TAIGA_URL: "http://10.241.13.163:9000"`, everything began to work.

**Comment by stefano-cherchi** [comment] 2021-03-16 13:31
> I tried this in Ubuntu 20.04 and ProtonOS 4.0RC both as VMs in VMware Workstation. The error message was displayed at http://localhost:9000 in both environments when used with the default docker-compose.yml file. After editing the docker-compose.yml file and modifying these lines
> ` TAIGA_SITES_DOMAIN: "localhost:9000"` && `TAIGA_URL: "http://localhost:9000"` to include the specific IP ` TAIGA_SITES_DOMAIN: "10.241.13.163:9000"` && `TAIGA_URL: "http://10.241.13.163:9000"`, everything began to work.

This is great, thank you. Had the same issue and, since I'm running Taiga behind a reverse proxy with SSL/TLS, I fixed it by just setting

`TAIGA_SITES_DOMAIN: "taiga.mydomanname.com"`

`TAIGA_URL: "https://taiga.mydomainname.com"`

**Comment by w1ck3dg0ph3r** [comment] 2021-04-13 06:24
Are you sure you're talking about this repo? There are no TAIGA_SITES_DOMAIN or TAIGA_URL env variables used here. It is controlled by TAIGA_HOST, TAIGA_SCHEME and TAIGA_PORT in variables.env.

**Comment by claranceliberi** [comment] 2021-09-08 15:33
> I tried this in Ubuntu 20.04 and ProtonOS 4.0RC both as VMs in VMware Workstation. The error message was displayed at http://localhost:9000 in both environments when used with the default docker-compose.yml file. After editing the docker-compose.yml file and modifying these lines
> ` TAIGA_SITES_DOMAIN: "localhost:9000"` && `TAIGA_URL: "http://localhost:9000"` to include the specific IP ` TAIGA_SITES_DOMAIN: "10.241.13.163:9000"` && `TAIGA_URL: "http://10.241.13.163:9000"`, everything began to work.

Thank you so much this helped me

**Comment by w1ck3dg0ph3r** [comment] 2021-11-29 06:25
Closing, as it seems to refer to official kaleidos docker images.

**Closed as completed by w1ck3dg0ph3r** 2021-11-29 06:25 UTC

**Comment by tammuoichanhoa** [comment] 2026-03-03 07:06
> I tried this in Ubuntu 20.04 and ProtonOS 4.0RC both as VMs in VMware Workstation. The error message was displayed at http://localhost:9000 in both environments when used with the default docker-compose.yml file. After editing the docker-compose.yml file and modifying these lines ` TAIGA_SITES_DOMAIN: "localhost:9000"` && `TAIGA_URL: "http://localhost:9000"` to include the specific IP ` TAIGA_SITES_DOMAIN: "10.241.13.163:9000"` && `TAIGA_URL: "http://10.241.13.163:9000"`, everything began to work.

Many thanks for your help. It works for me
