### ISSUE TITLE
Everything default with Something happened and our Oompa Loompas are working on it.

### ISSUE THREAD

**Issue by gerroon** [docker-taiga/taiga#33] opened 2020-04-18 16:29 UTC
Hi

I just cloned the git repo and only changed the ports (25080:80, no ssl) since I already have stuff running on those ports. And I am getting the message above.

There are no errors the docker logs that I can tell, and it is a long log.

I added taiga.lan to dns so it is resolvable as you see.
```
ping taiga.lan
PING taiga.lan (192.168.1.100) 56(84) bytes of data.
64 bytes from neoplecxus.com (192.168.1.100): icmp_seq=1 ttl=64 time=2.14 ms
```

The only thing I see is in the browser console
```
downloadable font: kern: Too large subtable (font-family: "OpenSans-Semibold" style:normal weight:400 stretch:100 src index:0) source: http://192.168.5.106:25080/v-1580925907841/fonts/OpenSans-Semibold.ttf
downloadable font: Table discarded (font-family: "OpenSans-Semibold" style:normal weight:400 stretch:100 src index:0) source: http://192.168.5.106:25080/v-1580925907841/fonts/OpenSans-Semibold.ttf
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://taiga.lan/api/v1/stats/discover. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://taiga.lan/api/v1/projects?discover_mode=true&is_featured=true. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://taiga.lan/api/v1/projects?discover_mode=true&order_by=-total_activity_last_week. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://taiga.lan/api/v1/projects?discover_mode=true&order_by=-total_fans_last_week. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://taiga.lan/api/v1/stats/discover. (Reason: CORS request did not succeed).
```

**Comment by w1ck3dg0ph3r** [comment] 2020-04-22 08:29
Hi!
In addition to changing port binding, you have to modify front-end config in `conf/front/config.json` to set `api` and `eventsUrl` to include the port number like so:
```json
{
    "api": "http://taiga.lan:25080/api/v1/",
    "eventsUrl": "ws://taiga.lan:25080/events/",
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 15000,
    "debug": true,
    "debugInfo": false,
    "defaultLanguage": "en",
    "publicRegisterEnabled": false,
    "gravatar": true,
    "feedbackEnabled": false,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": []
}
```
No container restart needed for that. Specifying custom ports through variables.env are not supported out of the box right now.

**Comment by alltheproject** [comment] 2020-04-22 13:07
Hi, I have the same problem. I have added the port in the file as you said and it s still not working. I still have : Something happened and our Oompa Loompas are working on it.

**Comment by gerroon** [comment] 2020-04-23 06:34
@w1ck3dg0ph3r

Thanks for the reply, your recommendation worked. 

I am still facing the same issue I had with the Vagrant setup :( The attachments do not work. I can upload them as far as I can tell but seeing them is not possible. Clicking on them gives me the infinite looping circle. I assume some another settings need to be set or something.

Also is there a place to set the file size limit?

**Comment by w1ck3dg0ph3r** [comment] 2020-04-28 07:40
@alltheproject Hi! Please, start a separate issue and add your environment and logs there, as it doesn't seem to be related to this.

**Comment by w1ck3dg0ph3r** [comment] 2020-04-28 07:47
@gerroon You can set client_max_body_size in nginx configuration in taiga-back and taiga-proxy. As for the attachments - I can't reproduce this in default setup. You can create separate issue and provide logs and redirection loop info. I'm closing this one, as the problem here seems to be resolved.

**Closed as completed by w1ck3dg0ph3r** 2020-04-28 07:47 UTC
